name: CICD

on:
  push: 
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup NET8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - run: pwd
      
      
          
#      - name: Restore dependencies
#        run: dotnet restore
      
      - run: ls -la
