name: Pull Request

on:
  workflow_dispatch:
  
  pull_request:
    # activity types
    types:
      - opened
#      - edited

  push: 
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello World
        run: echo Hello World!
